executors:
  j15:
    docker:
      - image: 'cimg/openjdk:15.0.1'
orbs:
  maven: circleci/maven@1.1
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          matrix:
            parameters:
              executor:
                - j15
